apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todos-fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jerrybaijy/todos-fullstack-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              value: "your-secret-key"
            - name: MYSQL_USER
              value: "todo_user"
            - name: MYSQL_PASSWORD
              value: "todo_password"
            - name: DB_HOST
              value: "mysql"
            - name: MYSQL_DATABASE
              value: "todos_db"
            - name: FLASK_APP
              value: "run.py"
            - name: FLASK_ENV
              value: "production"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: todos-fullstack
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP