apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-backend
  namespace: todos-fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-backend
  template:
    metadata:
      labels:
        app: todos-backend
    spec:
      containers:
      - name: backend
        image: jerrybaij/todos-fullstack-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: todos-secret
              key: SECRET_KEY
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: todos-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todos-secret
              key: MYSQL_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: todos-config
              key: DB_HOST
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: todos-config
              key: MYSQL_DATABASE
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              name: todos-config
              key: FLASK_APP
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: todos-config
              key: FLASK_ENV
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: todos-backend
  namespace: todos-fullstack
spec:
  selector:
    app: todos-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP