apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-frontend
  namespace: todos-fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-frontend
  template:
    metadata:
      labels:
        app: todos-frontend
    spec:
      containers:
      - name: frontend
        image: jerrybaij/todos-fullstack-frontend:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: todos-frontend
  namespace: todos-fullstack
spec:
  selector:
    app: todos-frontend
  ports:
  - port: 80
    targetPort: 80
  type: NodePort